Imports

In [25]:
import pandas as pd

Dataset loading and exploration

In [ ]:
oil_spill_dataset = pd.read_csv('../dataset/oil_spill.csv')
unique_values = oil_spill_dataset.nunique()
print(unique_values)

f_1       238
f_2       297
f_3       927
f_4       933
f_5       179
f_6       375
f_7       820
f_8       618
f_9       561
f_10       57
f_11      577
f_12       59
f_13       73
f_14      107
f_15       53
f_16       91
f_17      893
f_18      810
f_19      170
f_20       53
f_21       68
f_22        9
f_23        1
f_24       92
f_25        9
f_26        8
f_27        9
f_28      308
f_29      447
f_30      392
f_31      107
f_32       42
f_33        4
f_34       45
f_35      141
f_36      110
f_37        3
f_38      758
f_39        9
f_40        9
f_41      388
f_42      220
f_43      644
f_44      649
f_45      499
f_46        2
f_47      937
f_48      169
f_49      286
target      2
dtype: int64
Pregnancies                  17
Glucose                     136
BloodPressure                47
SkinThickness                51
Insulin                     186
BMI                         248
DiabetesPedigreeFunction    517
Age                          52
Outcome                       2
dtype: int64

Deleting colums that have only one unique value

In [32]:
for column in oil_spill_dataset.columns:
    if oil_spill_dataset[column].nunique() <= 1:
        oil_spill_dataset = oil_spill_dataset.drop(column, axis=1)
        print(f"Column '{column}' has been deleted.")

print(oil_spill_dataset)

Column 'f_23' has been deleted.
     f_1    f_2      f_3     f_4  f_5       f_6    f_7    f_8      f_9  f_10  \
0      1   2558  1506.09  456.63   90   6395000  40.88   7.89  29780.0  0.19
1      2  22325    79.11  841.03  180  55812500  51.11   1.21  61900.0  0.02
2      3    115  1449.85  608.43   88    287500  40.42   7.34   3340.0  0.18
3      4   1201  1562.53  295.65   66   3002500  42.40   7.97  18030.0  0.19
4      5    312   950.27  440.86   37    780000  41.43   7.03   3350.0  0.17
..   ...    ...      ...     ...  ...       ...    ...    ...      ...   ...
932  200     12    92.42  364.42  135     97200  59.42  10.34    884.0  0.17
933  201     11    98.82  248.64  159     89100  59.64  10.18    831.0  0.17
934  202     14    25.14  428.86   24    113400  60.14  17.94    847.0  0.30
935  203     10    96.00  451.30   68     81000  59.90  15.01    831.0  0.25
936  204     11     7.73  235.73  135     89100  61.82  12.24    831.0  0.20

     ...     f_41      f_42     f_43     f_44   f_45  f_46      f_47   f_48  \
0    ...  2850.00   1000.00   763.16   135.46   3.73     0  33243.19  65.74
1    ...  5750.00  11500.00  9593.48  1648.80   0.60     0  51572.04  65.73
2    ...  1400.00    250.00   150.00    45.13   9.33     1  31692.84  65.81
3    ...  6041.52    761.58   453.21   144.97  13.33     1  37696.21  65.67
4    ...  1320.04    710.63   512.54   109.16   2.58     0  29038.17  65.66
..   ...      ...       ...      ...      ...    ...   ...       ...    ...
932  ...   381.84    254.56    84.85   146.97   4.50     0   2593.50  65.85
933  ...   284.60    180.00   150.00    51.96   1.90     0   4361.25  65.70
934  ...   402.49    180.00   180.00     0.00   2.24     0   2153.05  65.91
935  ...   402.49    180.00    90.00    73.48   4.47     0   2421.43  65.97
936  ...   254.56    254.56   127.28   180.00   2.00     0   3782.68  65.65

     f_49  target
0    7.95       1
1    6.26       0
2    7.84       1
3    8.07       1
4    7.35       0
..    ...     ...
932  6.39       0
933  6.53       0
934  6.12       0
935  6.32       0
936  6.26       0

[937 rows x 49 columns]

Detecting outliers and dealing with them

In [ ]:
dataset_outliers = oil_spill_dataset.copy()
Q1 = dataset_outliers.quantile(0.25)
Q3 = dataset_outliers.quantile(0.75)
IQR = Q3 - Q1
outliers = ((dataset_outliers < (Q1 - 1.5 * IQR)) | (dataset_outliers > (Q3 + 1.5 * IQR))).sum()
print("Outliers detected:")
print(outliers)

Outliers detected:
f_1        15
f_2       107
f_3         0
f_4         6
f_5         0
f_6       132
f_7         1
f_8        38
f_9        99
f_10       29
f_11       70
f_12       58
f_13       77
f_14       16
f_15       35
f_16       20
f_17       67
f_18       55
f_19       95
f_20       30
f_21       80
f_22        0
f_24        0
f_25      136
f_26        0
f_27        0
f_28       43
f_29       79
f_30      100
f_31       33
f_32        0
f_33        4
f_34        0
f_35       87
f_36       86
f_37        0
f_38       55
f_39      136
f_40        0
f_41       79
f_42       75
f_43       66
f_44       64
f_45       57
f_46      120
f_47       72
f_48      136
f_49      136
target     41
dtype: int64
Dataset after removing outliers:
     f_1  f_2      f_3      f_4  f_5     f_6    f_7    f_8     f_9  f_10  ...  \
36    26   81  1705.68  1492.58   19  202500  35.65   6.32  2480.0  0.18  ...
50    40   98  1573.27  1055.45    2  245000  36.16   7.43  3570.0  0.20  ...
57    47  180  1740.51  1609.10  115  450000  35.61   6.89  3650.0  0.19  ...
60    50  194  1388.71  1768.67   65  485000  32.89   6.56  3610.0  0.20  ...
61    51   85  1729.00  1637.47   12  212500  35.98   7.46  2600.0  0.21  ...
..   ...  ...      ...      ...  ...     ...    ...    ...     ...   ...  ...
929  197   10    26.00   123.20   64   81000  58.80  11.33   794.0  0.19  ...
932  200   12    92.42   364.42  135   97200  59.42  10.34   884.0  0.17  ...
933  201   11    98.82   248.64  159   89100  59.64  10.18   831.0  0.17  ...
935  203   10    96.00   451.30   68   81000  59.90  15.01   831.0  0.25  ...
936  204   11     7.73   235.73  135   89100  61.82  12.24   831.0  0.20  ...

        f_41    f_42    f_43    f_44  f_45  f_46     f_47   f_48  f_49  target
36    901.39  269.26  178.33   59.63  5.05     0  3378.60  66.30  7.92       0
50    650.00  450.00  230.77  114.63  2.82     0  5149.36  66.07  7.91       0
57   1162.97  650.00  342.87  149.36  3.39     0  3776.92  66.36  7.92       0
60   1208.30  650.00  331.00  156.17  3.65     0  7624.18  66.39  7.44       0
61    873.21  412.31  175.40  102.93  4.98     0  3640.37  66.37  7.89       0
..       ...     ...     ...     ...   ...   ...      ...    ...   ...     ...
929   402.49  180.00   90.00   73.48  4.47     0  7162.29  65.50  6.43       0
932   381.84  254.56   84.85  146.97  4.50     0  2593.50  65.85  6.39       0
933   284.60  180.00  150.00   51.96  1.90     0  4361.25  65.70  6.53       0
935   402.49  180.00   90.00   73.48  4.47     0  2421.43  65.97  6.32       0
936   254.56  254.56  127.28  180.00  2.00     0  3782.68  65.65  6.26       0

[389 rows x 49 columns]

In [37]:
#Deleting rows with outliers
dataset_no_outliers = dataset_outliers[~((dataset_outliers < (Q1 - 1.5 * IQR)) | (dataset_outliers > (Q3 + 1.5 * IQR))).any(axis=1)]
print("Dataset after removing outliers:")
print(dataset_no_outliers)

Dataset after removing outliers:
     f_1  f_2      f_3      f_4  f_5     f_6    f_7    f_8     f_9  f_10  ...  \
36    26   81  1705.68  1492.58   19  202500  35.65   6.32  2480.0  0.18  ...
50    40   98  1573.27  1055.45    2  245000  36.16   7.43  3570.0  0.20  ...
57    47  180  1740.51  1609.10  115  450000  35.61   6.89  3650.0  0.19  ...
60    50  194  1388.71  1768.67   65  485000  32.89   6.56  3610.0  0.20  ...
61    51   85  1729.00  1637.47   12  212500  35.98   7.46  2600.0  0.21  ...
..   ...  ...      ...      ...  ...     ...    ...    ...     ...   ...  ...
929  197   10    26.00   123.20   64   81000  58.80  11.33   794.0  0.19  ...
932  200   12    92.42   364.42  135   97200  59.42  10.34   884.0  0.17  ...
933  201   11    98.82   248.64  159   89100  59.64  10.18   831.0  0.17  ...
935  203   10    96.00   451.30   68   81000  59.90  15.01   831.0  0.25  ...
936  204   11     7.73   235.73  135   89100  61.82  12.24   831.0  0.20  ...

        f_41    f_42    f_43    f_44  f_45  f_46     f_47   f_48  f_49  target
36    901.39  269.26  178.33   59.63  5.05     0  3378.60  66.30  7.92       0
50    650.00  450.00  230.77  114.63  2.82     0  5149.36  66.07  7.91       0
57   1162.97  650.00  342.87  149.36  3.39     0  3776.92  66.36  7.92       0
60   1208.30  650.00  331.00  156.17  3.65     0  7624.18  66.39  7.44       0
61    873.21  412.31  175.40  102.93  4.98     0  3640.37  66.37  7.89       0
..       ...     ...     ...     ...   ...   ...      ...    ...   ...     ...
929   402.49  180.00   90.00   73.48  4.47     0  7162.29  65.50  6.43       0
932   381.84  254.56   84.85  146.97  4.50     0  2593.50  65.85  6.39       0
933   284.60  180.00  150.00   51.96  1.90     0  4361.25  65.70  6.53       0
935   402.49  180.00   90.00   73.48  4.47     0  2421.43  65.97  6.32       0
936   254.56  254.56  127.28  180.00  2.00     0  3782.68  65.65  6.26       0

[389 rows x 49 columns]